### ISSUE TITLE
St_shortestpath driver metadata

### ISSUE THREAD

**Issue by ebocher** [orbisgis/gdms-topology#16]
The St_ShortestPath function must return a geometry set with a curve dimension constraint (equal to 1).
It seems done with the  GraphMetadataFactory. createEdgeMetadataShortestPath() in GraphPath.findPathBetween2Nodes but the orbisgis renderer is not able to analyse this constraint and display a linesymbolizer but a point.
We must ensure that this tablefunction will be display like a line and may be relate this pb to SE core  ?
@agueganno @agouge

**Comment by agueganno** [comment]
I'll have a look as soon as possible. Please send me a data set I can to 
work with.
