### ISSUE TITLE
Add strahler number algorithm

### ISSUE THREAD

**Issue by ebocher** [orbisgis/gdms-topology#17]
A description is available at http://en.wikipedia.org/wiki/Strahler_number

**Comment by agouge** [comment]
This should be fairly easy to implement using a depth-first search (DFS), though the given network will most likely have to be pre-processed and/or simplified to make sure it is a tree.

**Comment by agouge** [comment]
As of agouge/graphhopper-sna#7, Strahler has been implemented. All that remains is to write an SQL function in GDMS-Topology.

**Comment by agouge** [comment]
As of #25, this functionality is now included. See the [tutorial](https://github.com/agouge/gdms-topology/wiki/Strahler-stream-order).
