### ISSUE TITLE
Improve the way ST_Graph determines orientation

### ISSUE THREAD

**Issue by agouge** [orbisgis/gdms-topology#27]
In the current implementation, ST_Graph uses the order of the geometry coordinates to determine orientation. In addition, undirected edges are currently represented by two directed edges.

It would be nice to have the option of using a user-provided orientation field to determine orientation. That is, the user specifies in an added field whether the edge is to be oriented in the same sense as the order of the geometry coordinates (directed) or in the opposite order (reversed). The user may also specify that a given edge is to be undirected, and this undirected edge should be represented internally as a single undirected edge, not as two separate directed edges.

**Comment by agouge** [comment]
As per our discussion today, the user will specify the name of a column (say `orientation`) which will contain integers representing the edge's orientation:
- 1 = Directed
- -1 = Reversed
- 0 = Undirected (Bidirectional)

If the user's input data contains an edge where the orientation is not specified, it will be up to him to decide whether to consider the edge as directed, reversed or undirected.
@ebocher @gpetit

**Comment by agouge** [comment]
In my GraphCreators, I will have to allow directed graphs to have bidirectional edges. They will most likely be represented internally (in JGraphT) as two directed edges, but the `edges` table should **not** contain two edges.

**Comment by ebocher** [comment]
Perfect

**Comment by agouge** [comment]
When we parse the orientation column, if we find values other than -1, 0 and 1, we will exclude these edges from the graph and warn the user (via the log). 
@ebocher

**Comment by ebocher** [comment]
Sounds good for me.

**Comment by agouge** [comment]
In fact ST_Graph completely ignores orientation. We take care of the orientation in the GraphCreators. We will still make use of "global" integers to be able to construct directed, reversed, or undirected graphs. But for directed and reversed graphs we should also be able to consider individual edges as directed, reversed or undirected.
@ebocher

**Comment by agouge** [comment]
A graph may have a **global** orientation of directed, reversed or undirected.

Undirected graphs consist of _only_ undirected edges.

A particular edge in a directed graph may be directed, reversed or undirected. The same is true of reversed graphs. Undirected edges are represented by two directed edges.

In total, that means that there are seven possibilities for an edge, depending on the global orientation of the graph and the individual edge orientation.

@ebocher

**Comment by agouge** [comment]
Note that in directed and reversed graphs, undirected edges are represented by directed edges in both directions.
