### ISSUE TITLE
Redo ST_(M)ShortestPath(Length)

### ISSUE THREAD

**Issue by agouge** [orbisgis/gdms-topology#41]
Redo these functions to use [Java Network Analyzer](https://github.com/agouge/Java-Network-Analyzer) for routing.

Concretely, there will be two overloaded functions `ST_ShortestPath` (for returning geometries) and `ST_ShortestPathLength` (for returning distances).
#### Possible signatures

In every case, the user must either specify the weights column (for weighted graphs) or enter `1` (for unweighted graphs). The orientation is optional; the graph is considered directed if the user omits it.
- **One-to-One** Calculate the shortest path (or all shortest paths) from node 34 to node 83. (Note here: It would also be interesting to calculate all shortest paths within a given distance tolerance. That is, propose alternate "almost shortest" paths.)

``` mysql
ST_ShortestPath(edges, 34, 83, 'weights_column' OR 1[, orientation])
```
- **One-to-All** Calculate all shortest paths from node 34 (and hence produce a shortest path tree, or something like it if multiple shortest paths are allowed):

``` mysql
ST_ShortestPath(edges, 34, 'weights_column' OR 1[, orientation])
```
- **Many-to-Many** Calculate all shortest paths from every source to every destination contained in the table `source_dest_table`. This table must contain two columns, `source` and `destination`, containing node ids. (Use a `Map<Integer, Set<V>>` to keep track of sources and destinations?)

``` mysql
ST_ShortestPath(edges, source_dest_table, 'weights_column' OR 1[, orientation])
```

@ebocher @gpetit

**Comment by agouge** [comment]
All twelve possible signatures may be expressed succinctly as

``` mysql
ST_ShortestPath(edges, source_dest_table OR source[, destination], 'weights_column' OR 1[, orientation])
```

**Comment by agouge** [comment]
Since ST_ShortestPath and ST_Distance were already taken, I decided to name this function ST_Distances, though the name can be changed (to replace ST_ShortestPath, for example).

**Comment by ebocher** [comment]
ST_Distance will replace ST_ShortestPathLength

**Comment by agouge** [comment]
OK, so I'll add a commit to #50 to remove the current ST_ShortestPathLength function.

**Comment by ebocher** [comment]
Perfect

**Comment by agouge** [comment]
@ebocher Let me know when you've tested #50 and are happy with it so that we can close this issue.

**Comment by agouge** [comment]
Actually we can't close this yet because I still have to redo ST_ShortestPath.

**Comment by ebocher** [comment]
It will be cool to update the functions to permit something like
many to all 
ie 5 hospitals to all other nodes in the graph so the table schema must contain only a source column.

**Comment by agouge** [comment]
OK I'll look into this.

**Comment by agouge** [comment]
Now the possible signatures may be expressed as:

``` mysql
ST_ShortestPathLength(edges, source_dest_table | source[, destination][, 'weights_column'][, 'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected']);
```

If `'weights_column'` is omitted, the graph is considered to be unweighted.

`'edge_orientation_column'` is a column of integers in the `edges` table specifying the orientation of each edge:
- 1 - directed
- -1 - reversed
- 0 - undirected

**Comment by ebocher** [comment]
ST_MShortestPath() must changed to support as inputs :   
- argument 1 : the edges table,
- argument 2 :  a table with source and destination nodes

The output result must a table with the following schema
- source and destination columns,
- edge id,
- start and end node to the edge
- edge order
