### ISSUE TITLE
Create an icon

### ISSUE THREAD

**Issue by agouge** [orbisgis/gdms-topology#68]
In OrbisGIS's Plugin Manager, GDMS-Topology doesn't have an icon yet.

**Comment by gpetit** [comment]
Do you need some help ?

**Comment by agouge** [comment]
Sure!

**Comment by gpetit** [comment]
Is there a predefined size for the png ?

**Comment by agouge** [comment]
Here is the [noisemap icon](https://github.com/irstv/noisemap/blob/master/src/main/resources/icon.png). It seems to be 32x32. @nicolas-f Do you confirm?

**Comment by nicolas-f** [comment]
Yes 32x32

**Comment by nicolas-f** [comment]
'cause I like power of two. Computer scientist illness..
